  name: demo cicd
  
  on:
    workflow_dispatch:
  jobs:  
    executing-the-cmd:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6
   
        - name: exectingthe ls command
          run: ls -a
